### ISSUE TITLE
how can i display a popup with the results of a related query?

### ISSUE THREAD

**Issue by agaffiga** [jgravois/esri-leaflet-related#16]
Please tell me the right place to ask a question if this is the wrong place.

Do you have any examples of combining a related query with bindPopup? I've taken a stab at it, and it seems my pop up is one click behind the information I clicked on when I embed the call to related query within bindPopup().

Thank you from a newbie!

**Comment by jgravois** [comment]
> it seems my pop up is one click behind...

if the initial click on the marker/path/polygon is what you're using to trigger the async request to fetch related records, it definitely will be.  luckily you can call [`L.Layer.openPopup()`](http://leafletjs.com/reference-1.0.0.html#marker-openpopup) instead of waiting for someone to click on the same feature again.

```js
query.objectIds([currentFeatureId]).relationshipId("0").run(displayPopup)

function displayPopup (error, response, raw) {
  var currentFeature = fl.getFeature(currentId)
  currentFeature.bindPopup('matching rows: ' + response.features.length);
  currentFeature.openPopup();
}
```
another option would be to trigger the relationship query earlier on and bind your popups *before* a user click. 

either way, i think the example i outlined above would be a lot more useful in the [readme](https://github.com/jgravois/esri-leaflet-related#example) than what i have currently.  are you interested in submitting a pull request to make the update?

**Comment by agaffiga** [comment]
Thanks for your response. I ended up skipping bindPopup and setting a map.on(“click”) listener that grabs the related records, puts it into a new popup, and then opens the pop up. It works well!

I think your way below is simpler though.


To make the pull request, am I just editing the ReadMe with your example below?

Thanks again!
Ann

Ann Gaffigan
Owner/CEO
Gazelle Incorporated
714-793-9739

**Comment by jgravois** [comment]
> To make the pull request, am I just editing the ReadMe with your example below?

yes, exactly.  that way its front and center for other folks to find in the future.  bumping the versions of leaflet and esri-leaflet in that sample would probably be a good idea too.

```html
<!-- Load Leaflet from CDN-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/leaflet/1.0.0-rc.3/leaflet.css" />
<script src="https://cdn.jsdelivr.net/leaflet/1.0.0-rc.3/leaflet.js"></script>

<!-- Load Esri Leaflet from CDN -->
<script src="https://cdn.jsdelivr.net/leaflet.esri/2.0.2/esri-leaflet.js"></script>
```
